# @host = http://localhost:5119
@host = https://localhost:7232
@adminId = 558B31BC-B546-4187-AC45-B247C3B37326
@WebToken = DoesNotYetAdded


POST {{host}}/Subscriptions
Content-Type: application/json
# Authorization: bearer {{WebToken}}

{
  "SubscriptionType": "Free",
  "AdminId": "{{adminId}}"
}
###

# # Response:
# # {
# #   "Id": "{{adminId}}",
# #   "SubscriptionType": "Free", //"Starter", "Pro"
# # }