@host = http://localhost:5119
@host = https://localhost:7232
@gymId = 89c9e3a8-456a-46c3-ba36-6bd0fda8b795
//@subscriptionId = 92861a95-7cf6-432f-abbb-10b9500f92de
@subscriptionId = 161c662c-c8eb-4130-b925-936775f4be6b


GET {{host}}/subscriptions/{{subscriptionId}}/gyms/{{gymId}}
Content-Type: application/json
###
