@host = http://localhost:5119
@host = https://localhost:7232
@subscriptionId = 92861a95-7cf6-432f-abbb-10b9500f92de


GET {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json

###
